name: Update Group Website

on:
  workflow_dispatch:

jobs:
  Update_website:
    name: Updating website
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH
        uses: MrSquaare/ssh-setup-action@v1
        with:
          host: github.com
          private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Clone repositories
        run: |
          git clone git@github.com:kerzendorf-group/group-data.git
          git clone git@github.com:harshulgupt/groupwebsite_generator.git
          git clone git@github.com:kerzendorf-group/kerzendorf-group.github.io.git

      - name: List clones
        run: |
          ls -a

      - name: Clear cloned website repo
        run: |
          cd kerzendorf-group.github.io
          rm -rf *.html
          rm -rf assets images people sub_research

      - name: Setup directories inside kerzendorf-group.github.io
        run: |
          cd kerzendorf-group.github.io
          mkdir people sub_research
          cp -r ../groupwebsite_generator/assets ./
          cp -r ../group-data/images ./

      - name: Install Jupyter and Python3
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          sudo -H pip3 install --upgrade pip
          pip3 install jupyter

      - name: Run Notebooks
        run: |
          cd groupwebsite_generator
          jupyter nbconvert --to python notebooks/*.ipynb
          for python_file_name in $(find notebooks -name "*.py")
            do
              python3 "$python_file_name"
            done

      - name: Push Website
        env:
          ACCESS_DATA: ${{ secrets.ACCESS_DATA }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          cd kerzendorf-group.github.io
          git add .
          git commit -m "Pushed from website generator"
          git push
