name: Update Group Website

on:
  workflow_dispatch:
  repository_dispatch:
    types: [repo-push]
  push:
    branches:
      - main

jobs:
  update_website:
    name: Updating website
    runs-on: ubuntu-latest
    steps:
      - name: Clone groupwebsite_generator
        uses: actions/checkout@v4
        with:
          path: groupwebsite_generator

      - name: Clone group-data
        uses: actions/checkout@v4
        with:
          repository: kerzendorf-group/group-data
          path: group-data
          token: ${{ secrets.TARDIS_BOT_TOKEN }}

      - name: Clone kerzendorf-lab.github.io
        uses: actions/checkout@v4
        with:
          repository: kerzendorf-lab/kerzendorf-lab.github.io
          path: kerzendorf-lab.github.io
          token: ${{ secrets.TARDIS_BOT_TOKEN }}

      - name: Clone Research and News data
        uses: actions/checkout@v4
        with:
          repository: tardis-sn/research_news
          path: research_news
          token: ${{ secrets.TARDIS_BOT_TOKEN }}

      - name: Set up Python3
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Update pip and install Jupyter, Pandas and Pillow
        run: |
          pip install --upgrade pip jupyter pandas Pillow

      - name: Clear and setup directories inside kerzendorf-lab.github.io
        run: |
          ./notebooks/setup.sh
        working-directory: ./groupwebsite_generator

      - name: Run Notebooks
        run: |
          jupyter nbconvert --to python create_htmls.ipynb
          python3 create_htmls.py
        working-directory: ./groupwebsite_generator/notebooks

      - name: Push Website
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add .
          git commit --allow-empty -m "Push from website generator"
          git push
        working-directory: ./kerzendorf-lab.github.io
